#!/usr/bin/env bash
set -euo pipefail
trap 'e=$?; [ $e -ne 0 ] && echo "$0 exited in error"' EXIT
[ -v DRYRUN ] && DRYRUN=echo || DRYRUN=
source /opt/ni_tools/lncdshell/utils/waitforjobs.sh

#
# run tat2 script for all 7T funcs
#  20210915WF  init
test -d out || mkdir $_
MAXJOBS=10

idlist=($(selld8 l |grep -i 'Scan.*BrainMechR01'|cut -f1))
for id in ${idlist[@]}; do
   #inputs=($(ls /Volumes/Hera/preproc/7TBrainMech{_rest/MHRest_nost_ica/$id/,_mgsencmem/MHTask_nost/$id/*/}wdkm_func.nii.gz || :))
   inputs=($(ls /Volumes/Hera/preproc/7TBrainMech_rest/MHRest_nost_ica/$id/wdkm_func.nii.gz 2>/dev/null || :))
   [ ${#inputs[@]} -lt 1 ] && echo "WARNING: no files for $id; pp 7TBrainMech_rest MHRest_nost_ica" && continue
   [ -r out/${id}_tat2.nii.gz ] && continue
   echo "# $id ${#inputs[@]}"
   # original censor file used. generated by FC's scripts? 
   motion_file="motion_info/censor_custom_fd_0.3_dvars_Inf.1d"
   # 20220301 - motion created by preprocessFunctional
   [ ! -r $(dirname ${inputs[0]})/"$motion_file" ] && motion_file="motion_info/fd_0.3_censor.1D"
   $DRYRUN tat2 -output out/${id}_tat2.nii.gz -no_voxscale -mean_time -median_vol -censor_rel "$motion_file" "${inputs[@]}" &
  waitforjobs
done
wait

