site_name: 7T BrainMechR01 Scripts
repo_url: https://github.com/LabNeuroCogDevel/7TBrainMech_scripts
theme:
  name: material
  features:
   - content.code.annotate
plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
