#' p-value or t-value
#' returns whichever model supports
#' @param cf single coefficent row from model summary.
#' @param asllist boolean to return list instead of string
#' @export
p_or_t <- function(cfs, aslist=F) {
  if ("Pr(>|t|)" %in% names(cfs))
     sig <- list(m="p", v=cfs["Pr(>|t|)"])
  else
     sig <- list(m="t", v=cfs["t value"])

  if(aslist) return(sig)

  do.call(paste, c(sep=": ", sig))
}

#' @title what y: age2 invage or age
#' @description returns which age was modeled
#' @param cfs coefficent table from model summary.
#' @export
what_age_y <- function(cfs) {
  bestfit <- case_when( 'age2' %in% row.names(cfs) ~ 'age2',
                        'invage' %in% row.names(cfs) ~ 'invage',
                        TRUE ~ 'age')
}


#' CRLB clean
#' add ages, remove bad crlb
#' @param d dataframe with ld8, region, metabolite, and CRLB columns
#' @param regions numeric regions vector to include
#' @import dplyr
#' @export
mrsi_clean <- function(d, regions, CRLB, crlb_thres=20, mesg=F) {
  # make nonline age columns if we don't already have them
  if(! 'invage' %in% names(d)) d$invage <- 1/d$age
  if(! 'age2'   %in% names(d)) d$age2   <- d$age^2

  # Filtering
  brain_region_all <- d %>% filter(roi %in% regions)
  # for debuging e.g.: CRLB <- quo(Clu.SD)
  brain_region <-
    brain_region_all %>%
    filter(!!enquo(CRLB) <= crlb_thres) %>%
    na.omit()

  #MESG: return sample size so i know how many people i now have after exclusions

  if(mesg) cat(sprintf("region(s) %s, %s > %d: retaining %d/%d\n",
              paste(collapse=",", regions),
              as.character(substitute(CRLB)), crlb_thres,
              nrow(brain_region), nrow(brain_region_all)))

  return(brain_region)
}

#' @title
#' find best MRSI data model fit
#' @description
#' pick lowest AIC model among lin, inv, and quad w/rand effects if more than one region
#' @param d dataframe with ld8, region, metabolite, and CRLB columns
#' @param regions numeric regions vector to include
#' @import dplyr
#' @importFrom lme4 lmer
#' @export
mrsi_bestmodel <- function(d, regions, metabolite, CRLB, crlb_thres=20) {
  require(dplyr)

  brain_region <- mrsi_clean(d, regions, !!enquo(CRLB), crlb_thres)

  mtbl_str <- as.character(substitute(metabolite))
  # for debug: metabolite <- quo(Glu.Cr)
  # mtbl_str <- 'Glu.Cr'

  # AGE EFFECT
  # Test linear, inverse, and quadratic fits

  # models - 1st %s replaced w/ metabolite
  #        - 2nd %s replaced w/ nuissance (GMrat, maybe label and random eff)
  models_strs <-
      list(age   ="%s ~ age        + %s",
           invage="%s ~ invage     + %s",
           age2  ="%s ~ age + age2 + %s")

  # default to 
  # nuisance just GM ratio and using `lm`
  nuissance <- "GMrat"
  mdlfunc <- lm

  # if we have more than one region, add label and random effect of subject
  # also need to use lmer instead of lm
  if (length(regions) > 1) {
     nuissance <- paste0(nuissance, '+ label + (1|ld8)')
     mdlfunc <- lme4::lmer
  }

  # fill in formula and calculate model
  models <- lapply(models_strs, function(fmlstr)
                   sprintf(fmlstr, mtbl_str, nuissance) %>% as.formula %>% mdlfunc(brain_region))
  AICs <- sapply(models, AIC)

  # find which is the best based on AIC
  bestfit <- names(AICs)[which.min(AICs)] # age, invage, or age2
  best_model <- models[[bestfit]]

  cfs <- summary(best_model)$coefficients[bestfit, ]
  sig = p_or_t(cfs)
  #MESG: return sample size so i know how many people i now have after exclusions
  cat(sprintf("%s region(s) %s: best=%s (AIC%.03f, %s)\n",
              mtbl_str,paste(regions), bestfit, min(AICs), sig))

 return(best_model)
}


#' @title
#' get estimates from the best model
#' @description
#' returns estimate dataframe for plotting.
#' includes p and beta columns (same value repeated in ea. row)
#' @param m  model generated by [mrsi_bestmodel()]
#' @importFrom emmeans ref_grid
#' @export
mrsi_fitdf <- function(m) {
  # todo: get brain_regions and best fit from model

  # reconstruct what age was used for this model
  cfs <- summary(m)$coefficients
  bestfit <- what_age_y(cfs)

  # need max age
  # get data frame from model (different for lme4 and lm)
  if (isClass("lme4", m)) d <- m@frame
  else                  d <- m$model
  # and get age range (different for invage)
  if (bestfit == "invage") ages <- range(1/d$invage)
  else                    ages <- range(d$age)

  # assume first element in RHS of forumal is metabolite
  # should maybe be something passed in to the function?
  mtbl_str <- names(d)[1]
  # what to use as age column to use as input for emmeans
  # age2 needs 2 columns (age + age2)
  interp_age <- seq(ages[1], ages[2], by=.1)

  if (bestfit == "age") {
    best_list <- list(age=interp_age)
  } else if (bestfit=="invage") {
    best_list <- list(invage=1/interp_age)
  } else if (bestfit=="age2") {
    best_list <- list(age=interp_age, age2=interpage^2)
  } else {
      stop("unknown best AIC model!", bestfit)
  }

  avgs <- emmeans::ref_grid(m, at=best_list)
  fitdf <- as.data.frame(summary(avgs))

  # will want age for plotting. add back if we dont have it (invage fit)
  # N.B. if we mean center inv age, this wont be as easy to revert
  if (bestfit == "invage") fitdf$age <- 1/fitdf$invage

  fitdf$bestfit <- bestfit
  fitdf$metabolite <- mtbl_str
  fitdf$beta <- cfs[bestfit, "Estimate"]
  fitdf$tval <- cfs[bestfit, "t value"]

  return(fitdf)
}
