#!/usr/bin/env Rscript
library(dplyr)
# 20240314WF - copy of UPPS.R but reworked for RT-18
# confirmed Qs from https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3160867/
# selfreports generated by 000_getQualtrics.R
extract_question_range<-function(f, firstq, lastq, nquests)	{
   d <- read.csv(f)
   # find first question
   i <- grep(pattern=firstq, t(d[1,]), ignore.case=T)[1]
   if(is.na(i)) stop("missing starting RT18 question in ",f)

   # confirm last question is expected
   last_i <- i+ (nquests - 1)
   last_q <- d[1,last_i]
   if(!grepl(lastq, last_q))
      stop("start at ",i," but hit bad last question on ", last_i," column of",f, " ",last_q,"\n")
   rng <- i:last_i
   # extract data
   # if there are multiple rows, the last is what we want (other is maybe question metadata)
   r <- d[nrow(d),rng]
   
   # name with question
   names(r) <- unname(d[1,rng]) 

   return(r)
}

FIRST_TEXT <- 'I sometimes do "crazy" things just for fun.'
LAST_TEXT  <- 'I often spend money until [Ii] run out of cash or get into debt from using too much credit'
N_QUESTS <- 18
extract_rt18 <- function(f) extract_question_range(f, FIRST_TEXT, LAST_TEXT, N_QUESTS)
write_rt18 <- function() {
   l <- Sys.glob('/Volumes/L/bea_res/Data/Temporary Raw Data/7T/*/*_selfreport.csv')
   rt18_all <- lapply(l,\(f) tryCatch(extract_rt18(f),error=function(e) {print(e); NULL}))
   keep_files <- !sapply(rt18_all,is.null)
   ld8 <- sapply(l[keep_files],stringr::str_extract,'\\d{5}_\\d{8}')
   rt18 <- bind_rows(rt18_all)

   # extract luna_date
   rt18_out <- rt18 %>% mutate(ld8=ld8)
   write.csv(rt18_out, 'txt/rt18.csv',row.names=F)
}
# when run as script
if(sys.nframe()==0) write_rt18()
