#!/bin/bash

# xxxxxxxxVI: Originally MRSI_CoregSeg_MB4_plusExtras.bash
# 20181213WF: modified for lncd files
#
# wrapper for matlab:
#  Divide ROI & Resize Scout to 1mm 
#  Coregistration (MPRAGE to Scout) & linear regression
#  estimate probability of FS ROI @ each csi voxel

set -euo pipefail
export AFNI_COMPRESSOR="" AFNI_NIFTI_TYPE_WARN=NO

if [ $# -eq 0 ]; then
   cat <<HEREDOC 
   USAGE:
     $0 subj_date [scout_slice_num=17]
     # see /Volumes/Hera/Projects/7TBrainMech/pipelines/MHT1_2mm/ for subj list
HEREDOC
  exit 1
fi

## read subject input

# user input
subj_date=$1

# slice numbers of SCOUT corresponding to the center positions of CSI acquisition 
#   add 1 to Siemens Slice number in header
[ $# -eq 1 ] && scout_slice_num=17 || scout_slice_num="$2"

# files
subj=${subj_date%%_*}
FSdir=/Volumes/Hera/Projects/7TBrainMech/FS/$subj/ 
scout="/Volumes/Hera/Projects/7TBrainMech/subjs/$subj_date/slice_PFC/slice_pfc.nii.gz"
# no need for mprage -- using freesurfer's orig.nii
# could use link
#filename_MRSI=spreadsheet  # MRSI excel file name after excluding '_SI*'

check_file(){
    file="$1";shift
    msg="$1";shift
    [ -r "$file" ] && return
    echo "$subj_date: no file: $file"
    echo "  # fix: $msg" 
    exit 1
}

check_file "$scout"                     "run ./01_get_slices.bash"
check_file "$FSdir/mri/aparc+aseg.mgz"  "run ../FS/002_fromPSC.bash"

data_dir="/Volumes/Hera/Projects/7TBrainMech/subjs/$subj_date/slice_PFC/MRSI"
[ ! -d $data_dir ] && mkdir $data_dir

############################ depends #############################################

# where are the matlab toolboxes and code
matlabcode_dir=$(cd $(dirname $0);pwd)/Codes_yj/
spm_dir=/opt/ni_tools/matlab_toolboxes/spm12/
nifti_dir=$matlabcode_dir/NIfTI

# where to save everything
# where to save the grouped FS parcelations rois
ROI_dir=$data_dir/parc_group
# where to save matlab log
log_reg=$data_dir/Log_Regression.out
# No FLAIR, so empty filename
filename_flair=""; 


## UNUSED, prob thres (should be between 0 and 1)
thresh_total=0.75     # GM + WM > thresh_total 
thresh_maxtissue=0.5  # Fraction of Max Region > thresh_maxtissue

###################### make files   ############################################

[ -e $log_reg ] && echo "Deleting log file for linear regression"   && rm $log_reg
# is this a good idea?
[ -d $ROI_dir ] && echo "Deleting parc grouping directory $ROI_dir" && rm -r $ROI_dir
[ ! -d $ROI_dir ] && mkdir -p $ROI_dir


cd $data_dir
mgz2nii_RAS() { 
   # freesurfer mgz into nii (w/ RAS matrix orientation)
   mri_convert --in_type mgz --out_type nii --out_orientation RAS \
      $FSdir/mri/$1.mgz $1.nii
   # AFNI converts NIFTI_datatype=8 (INT32) to FLOAT32
   3dcopy $1.nii  $ROI_dir/$1.nii
   # remove mri_convert (INT32) version
   rm $1.nii
}

mgz2nii_RAS orig
mgz2nii_RAS aparc+aseg
mgz2nii_RAS wmparc

# scout in data dir for matlab resize
3dcopy -overwrite $scout scout.nii
# csi_template used to make nifti from 2d mat csi outputs
3dcopy -overwrite $(dirname $scout)/s17/9x9mm.nii.gz csi_template.nii


mscript=fs_csi_${subj_date}.m  
cat > $mscript <<EOF
% generated by $0 ($(pwd)) on $(date)
addpath('$nifti_dir');
addpath('$spm_dir');

matlabcode_dir='$matlabcode_dir';
ROI_dir='$ROI_dir';
data_dir='$data_dir';
roi_file='$matlabcode_dir/../roi.txt';
csi_json='$matlabcode_dir/../csi_settings.json';
filename_scout='scout.nii';
filename_flair='$filename_flair';

cd(matlabcode_dir);
grouping_masks(roi_file, ROI_dir) 
img_resize_ft(data_dir,filename_scout);
spm_reg_ROIs(ROI_dir, roi_file, fullfile(data_dir,filename_scout), filename_flair) 
csi_roi_label(ROI_dir, roi_file, csi_json, filename_flair,$scout_slice_num)
% makes 2d_csi_ROI and struct_ROI directories

% make niftis
csi_2d_dir = fullfile(data_dir,'2d_csi_ROI');
dir2d_to_niis(csi_2d_dir,csi_2d_dir, fullfile(data_dir,'csi_template.nii'));
EOF

echo "# running $(pwd)/$mscript"

### actually run!
# -nodesktop -nosplash 
matlab -nodisplay -r "try, ${mscript%.m}, end; quit" |tee $log_reg
