.make/pyrecon.list: $(wildcard /Volumes/Hera/Raw/MRprojects/7TBrainMech/*/S*/B1MapHomog/B1.1.0.1.1.1') | .make/
	./01_chanb1.py
	mkls $@ /Volumes/Hera/Raw/MRprojects/7TBrainMech/2*/SHIM/B1MapHomog/b1-pyrecon.nii.gz


%/:
	mkdir $@
